### ISSUE TITLE
Rewrite a safe version of the SHA256 library

### ISSUE THREAD

**Issue by tekkac** [bitcoin-stark/khepri-starknet#36]
## Description
  Fix the implementation of SHA256 so that it verifies the output via `finalize_sha256`.
## Context
  The [official Cairo SHA256 library](https://github.com/starkware-libs/cairo-examples/tree/master/sha256) only handles up to 55 bytes length inputs. Our ad-hoc version can handle input up to 80 bytes, however it is unsafe as the hint verification is [skipped](https://github.com/bitcoin-stark/khepri-starknet/blob/ec3ec36e56c48906acb837461366af2d12afa44d/src/utils/sha256/sha256_contract.cairo#L19).

## Suggestion
  Write a safe Cairo SHA256 library, based on the official one, that can handle arbitrary size inputs. This could be done as an external library that would replace the one in `src/utils/sha256/`

**Comment by Th0rgal** [comment]
Hey there, should this function supports any bit length, multiple of 32 bits or multiple of 8 bits?

**Comment by tekkac** [comment]
@Th0rgal porting the existing code to multiples of 8 bits should be the easiest way to go.
Extending to arbitrary bit length is not needed here but a must have if you want to compute the actual SHA256 function.

**Comment by Th0rgal** [comment]
Here we go: https://github.com/Th0rgal/sphinx#sha256
This supports any bit length that fits in 32 bits (so about 8.6 GB). This could be tweaked to support up to 64 bits but I don't think this is useful for now. If you like it, I could work on it and try to improve the performances.

**Comment by AbdelStark** [comment]
Thanks @Th0rgal for your contribution
The implementation is available here: https://github.com/CairOpen/cairopen-contracts/tree/main/src/cairopen/hash#sha256-computation
